### ISSUE TITLE
Error during CSV generation

### ISSUE THREAD

**Issue by dominicbartl** [freshfox/navory#45]
During an export the following error occured:

```
0|start    | TypeError: Cannot read property 'date' of undefined
0|start    |     at ExportService._transformExpensesForBMD (/opt/navory/dist/app/services/export_service.js:405:75)
0|start    |     at expenses.map (/opt/navory/dist/app/services/export_service.js:160:50)
0|start    |     at Array.map (<anonymous>)
0|start    |     at Child.expenseRepo.listBetween.then (/opt/navory/dist/app/services/export_service.js:160:29)
0|start    |     at Child.tryCatcher (/opt/navory/node_modules/bluebird/js/release/util.js:16:23)
0|start    |     at Promise._settlePromiseFromHandler (/opt/navory/node_modules/bluebird/js/release/promise.js:512:31)
0|start    |     at Promise._settlePromise (/opt/navory/node_modules/bluebird/js/release/promise.js:569:18)
0|start    |     at Promise._settlePromise0 (/opt/navory/node_modules/bluebird/js/release/promise.js:614:10)
0|start    |     at Promise._settlePromises (/opt/navory/node_modules/bluebird/js/release/promise.js:694:18)
0|start    |     at _drainQueueStep (/opt/navory/node_modules/bluebird/js/release/async.js:138:12)
0|start    |     at _drainQueue (/opt/navory/node_modules/bluebird/js/release/async.js:131:9)
0|start    |     at Async._drainQueues (/opt/navory/node_modules/bluebird/js/release/async.js:147:5)
0|start    |     at Immediate.Async.drainQueues (/opt/navory/node_modules/bluebird/js/release/async.js:17:14)
0|start    |     at runCallback (timers.js:810:20)
0|start    |     at tryOnImmediate (timers.js:768:5)
0|start    |     at processImmediate [as _immediateCallback] (timers.js:745:5)
```

The line is:
```
buchdatum: Formatter.formatDateAsDMY(firstPayment.date),
```

There should be a test case for this as well

**Comment by dominicbartl** [comment]
I just checked the code again. I think the crash happens when the income/expense has a `price=0`. I think those can be skipped from the export as well. Don't forget to add a `price=0` expense in the test please
